[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [{ access = "read", path = "./broadcast" }]


remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@uniswap-v2-core=lib/v2-core/"]
solc = "0.8.18"

ignored_warnings_from = ["test/mock"]
compiler_warnings=["all"]

# [profile.coverage]
# exclude = ["script/*", "test/mock/*"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
uzh_eth = "${UZH_RPC_URL}"
 